name: gatk_align_and_preprocess
description: Perform variant calling on a set of normal samples using mutect2 panel of normals mode. Group them into a genomicsdbworkspace using genomicsdbimport, then use this to create a panel of normals using createsomaticpanelofnormals.
keywords:
  - gatk4
  - mutect2
  - genomicsdbimport
  - createsomaticpanelofnormals
  - variant_calling
  - genomicsdb_workspace
  - panel_of_normals
modules:
  - gatk4/mutect2
  - gatk4/genomicsdbimport
  - gatk4/createsomaticpanelofnormals
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false, read_group:'"@RG\\tID:Seq01p\\tSM:Seq01\\tPL:ILLUMINA"' ]
  - input:
      type: file
      description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively. Can also use ubams.
  - intervals:
      type: file
      description: Bed file with the genomic regions included in the library
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - bwaindex:
      type: file
      description: BWA genome index files, if this is not specified then fasta file will be used to generate it.
      pattern: "Directory containing BWA index *.{0132,amb,ann,bwt.2bit.64,pac}"
  - is_ubam:
      type: boolean
      description: |
          option to set whether input is an unaligned bam (true) or fastq (false),
          if true, it runs fastq conversion of the ubam file
      pattern: "{true,false}"
  - sort_order:
      type: value
      description: Picard sort order type for sorting prior to samtools indexing.
      pattern: "unsorted|queryname|coordinate|duplicate|unknown"
  - knownsites:
      type: file
      description: VCF file containing known sites (optional)
  - knownsites_tbi:
      type: file
      description: VCF index of dbsnp (optional)

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - bwa_index_out:
      type: file
      description: BWA genome index files
      pattern: "*.{0132,amb,ann,bwt.2bit.64,pac}"
  - fastq_out:
      type: file
      description: compressed FASTQ files
      pattern: "[*_1.fastq.gz , *_2.fastq.gz]"
  - bwa_mem_out:
      type: file
      description: Output BAM file containing read alignments
      pattern: '*.{mapped.bam}'
  - sortsam_unmapped_out:
      type: file
      description: Sorted unmapped BAM file containing read alignments
      pattern: '*.{unmapped.sorted.bam}'
  - merge_bam_out:
      type: file
      description: The merged bam file
      pattern: "*.{merged.bam}"
  - markdup_out:
      type: file
      description: BAM file containing read alignments with duplicates marked
      pattern: '*.{markduplicates.bam}'
  - metrics:
      type: file
      description: Duplicate metrics file generated by picard
      pattern: "*.{metrics.txt}"
  - sortsam_dupesmarked_out:
      type: file
      description: sorted BAM file containing read alignments with duplicates marked
      pattern: '*.{sorted.bam}'
  - samtools_index_out:
      type: file
      description: index file of the sorted and duplicate marked bam file.
      pattern: "*.{bai}"
  - baserecalibrator_out:
      type: file
      description: Recalibration table from BaseRecalibrator
      pattern: "*.{table}"
  - applybqsr_out:
      type: file
      description: Recalibrated BAM file
      pattern: "*.{recalibrated.bam}"
authors:
  - '@GCJMackenzie'
