name: gatk_joint_germline_variant_calling_skip_haplotc
description: |
  Perform variant calling on a multiple germline samples using haplotypecaller in GVCF mode.
  Run output gvcds through genomisdbimport together to create a joint genomicsdbworkspace, then run genotypeGVCFs on the workspace to get a joint calling vcf.
  Recalibrate joint vcf using step1 (VariantRecalibrator) and step2 (applyVQSR) of VQSR.
keywords:
  - gatk4
  - haplotypecaller
  - genomisdbimport
  - genotypegvcfs
  - variantrecalibrator
  - applyvqsr
  - variant_calling
  - joint_germline
  - VQSR
modules:
  - gatk4/haplotypecaller
  - gatk4/genomicsdbimport
  - gatk4/genotypegvcfs
  - gatk4/variantrecalibrator
  - gatk4/applyvqsr
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: list
      description: |
        list containing BAM files and their indexes to be run through haplotypecaller, also able to take CRAM as an input.
        OR if run_haplotc is false then it will contain gvcf files and their tbi indexes.
        e.g."[ [ id:'test' ], .{bam/cram}, {bam.bai/cram.crai} ]"
        OR "[[ id:'test' ], .g.vcf, .g.vcf.tbi]"
  - run_haplotc:
      type: boolean
      description: if true then run haplotypecaller portion of subworkflow, if false skip to genomicsdbimport
      pattern: "{true,false}"
  - run_vqsr:
      type: boolean
      description: if true then run vqsr portion of subworkflow, if false skip to end.
      pattern: "{true,false}"
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - sites:
      type: file
      description: Population vcf of germline sequencing, containing known sites.
      pattern: "*.vcf.gz"
  - sites_index:
      type: file
      description: Index file for the known sites.
      pattern: "*.vcf.gz.tbi"
  - joint_id:
      type: val
      description: joint id to replace individual sample ids with.
      pattern: "e.g. test_joint"
  - allelespecific:
      type: boolean
      description: run allelespecific mode of vqsr modules.
      pattern: "{true,false}"
  - resources:
      type: val
      description: |
        resource vcfs, indexes and labels to be used as truth, training and known sites resources,
        vcf list imports the files into the module,
        resource_labels list contains file names which are passed to the command.
      pattern: "[[resource, vcfs, forvariantrecal], [resource, tbis, forvariantrecal], [resource, labels, forvariantrecal]]"
  - annotation:
      type: list
      description: list of annotations to use for variantrecal filtering.
      pattern: "['QD', 'FS', 'SOR']"
  - mode:
      type: val
      description: which mode to run variantrecal and applyvqsr in, BOTH is only intended for testing and debugging purposes.
      pattern: "{SNP,INDEL,BOTH}"
  - create_rscript:
      type: boolean
      description: whether to generate rscript plots in variantrecal.
      pattern: "{true,false}"
  - truthsensitivity:
      type: val
      description: truthsensitivity cutoff for applyvqsr.
      pattern: "0.0-100.0"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - haplotc_vcf:
      type: file
      description: Compressed gvcf file from haplotypecaller.
      pattern: "[ *g.vcf.gz ]"
  - haplotc_index:
      type: file
      description: Indexes of the haplotypecaller_gvcf file
      pattern: "[ *g.vcf.gz.tbi ]"
  - genomicsdb:
      type: directory
      description: Genomicsddworkspace made using genomicsdbimport.
      pattern: "/genomicsdbworkspace"
  - genotype_vcf:
      type: file
      description: File containing the joint vcf file from genotypegvcfs.
      pattern: "*.vcf.gz"
  - genotype_index:
      type: file
      description: File containing the contamination table.
      pattern: ".vcf.gz.tbi"
  - recal_file:
      type: file
      description: recalibration tables file from variantrecalibrator.
      pattern: "*.recal"
  - recal_index:
      type: file
      description: Index file for the recalibration tables.
      pattern: "*.idx"
  - recal_tranches:
      type: file
      description: Tranches file for the recalibration tables.
      pattern: "*.tranches"
  - vqsr_vcf:
      type: file
      description: joint vcf file recalibrated using applyvqsr.
      pattern: "*.vcf.gz"
  - vqsr_index:
      type: file
      description: Index file for recalibrated joint vcf.
      pattern: "*.vcf.gz.tbi"
authors:
  - '@GCJMackenzie'
